[package]
name = "rusty-aquarium"
version = "0.8.0"
authors = ["Olle Wreede <olle@wreede.se>"]
edition = "2018"

[dependencies]
#macroquad = "0.3.0-alpha.17"
macroquad = { version = "0.3.2", git = "https://github.com/not-fl3/macroquad" }
macroquad-particles = { git = "https://github.com/not-fl3/macroquad" }
futures = "0.3.*"
nanoserde = "0.1.*"

# Doesn't work with android build
[profile.dev.package.'*']
opt-level = 3

[package.metadata.scripts]
build-web = "bin/build-web"
serve-web = "bin/serve-web"
build-win = "bin/build-win"
build-mac = "bin/build-mac"
build-apk = "bin/build-apk"
build-linux = "bin/build-linux"

[package.metadata.android]
assets = "assets"
