[package]
name = "rusty-aquarium"
version = "0.1.0"
authors = ["Olle Wreede <olle@wreede.se>"]
edition = "2018"

[dependencies]
macroquad = "0.3.0-alpha.15"

# Doesn't work with android build
[profile.dev.package.'*']
opt-level = 3

[package.metadata.scripts]
build-web = "bin/build-web"
serve-web = "bin/serve-web"
build-win = "bin/build-win"
build-apk = "bin/build-apk"
build-linux = "bin/build-linux"

[package.metadata.android]
assets = "assets"
